-- 第一批论坛迁移：服务端约束、幂等、软删除、限流和投票一致性。
-- 兼容旧数据；执行前请先导出 posts/comments/votes 的结构和计数快照。

create extension if not exists pgcrypto;

alter table public.posts add column if not exists request_id uuid;
alter table public.posts add column if not exists updated_at timestamptz not null default now();
alter table public.posts add column if not exists deleted_at timestamptz;
alter table public.comments add column if not exists request_id uuid;
alter table public.comments add column if not exists updated_at timestamptz not null default now();
alter table public.comments add column if not exists deleted_at timestamptz;
alter table public.comments add column if not exists author text;

update public.posts set updated_at = coalesce(updated_at, created_at, now()) where updated_at is null;
update public.comments set updated_at = coalesce(updated_at, created_at, now()) where updated_at is null;

alter table public.posts drop constraint if exists posts_title_length_check;
alter table public.posts add constraint posts_title_length_check check (char_length(btrim(title)) between 1 and 120);
alter table public.posts drop constraint if exists posts_content_length_check;
alter table public.posts add constraint posts_content_length_check check (content is null or char_length(btrim(content)) between 1 and 20000);
alter table public.posts drop constraint if exists posts_category_check;
alter table public.posts add constraint posts_category_check check (category in ('question','bug_report','showcase','general','skill_exchange','security_audit','review','other'));
alter table public.comments drop constraint if exists comments_content_length_check;
alter table public.comments add constraint comments_content_length_check check (char_length(btrim(content)) between 1 and 5000);

create unique index if not exists posts_user_request_id_idx on public.posts(user_id, request_id);
create unique index if not exists comments_user_request_id_idx on public.comments(user_id, request_id);
create index if not exists posts_public_created_idx on public.posts(created_at desc, id desc) where deleted_at is null;
create index if not exists posts_public_hot_idx on public.posts(upvotes desc, replies desc, created_at desc, id desc) where deleted_at is null;
create index if not exists comments_public_post_idx on public.comments(post_id, created_at asc) where deleted_at is null;

update public.posts p set replies = (select count(*) from public.comments c where c.post_id = p.id and c.deleted_at is null);

drop policy if exists "Anyone can read posts" on public.posts;
create policy "Anyone can read posts" on public.posts for select using (deleted_at is null);
drop policy if exists "Users can update their own posts" on public.posts;
create policy "Users can update their own posts" on public.posts for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users can delete their own posts" on public.posts;
create policy "Users can delete their own posts" on public.posts for delete to authenticated using ((select auth.uid()) = user_id);

drop policy if exists "Anyone can read comments" on public.comments;
create policy "Anyone can read comments" on public.comments for select using (deleted_at is null);
drop policy if exists "Users can update their own comments" on public.comments;
create policy "Users can update their own comments" on public.comments for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "Users can delete their own comments" on public.comments;
create policy "Users can delete their own comments" on public.comments for delete to authenticated using ((select auth.uid()) = user_id);

create table if not exists public.forum_action_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null check (action in ('post','reply','vote')),
  request_id uuid,
  created_at timestamptz not null default now()
);
create unique index if not exists forum_action_request_idx on public.forum_action_log(user_id, action, request_id) where request_id is not null;
create index if not exists forum_action_window_idx on public.forum_action_log(user_id, action, created_at desc);
alter table public.forum_action_log enable row level security;
revoke all on public.forum_action_log from anon, authenticated;

create or replace function public.check_forum_rate_limit(p_action text, p_request_id uuid default null)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  current_user_id uuid := auth.uid();
  max_per_minute integer;
  already_seen boolean;
  used_count integer;
begin
  if current_user_id is null then raise exception 'not_authenticated'; end if;
  if p_action not in ('post','reply','vote') then raise exception 'invalid_action'; end if;
  max_per_minute := case when p_action = 'vote' then 60 else 10 end;
  perform pg_advisory_xact_lock(hashtextextended(current_user_id::text || ':' || p_action, 0));
  select exists(select 1 from public.forum_action_log where user_id = current_user_id and action = p_action and request_id = p_request_id) into already_seen;
  if already_seen then return jsonb_build_object('allowed', true, 'retry_after', 0, 'duplicate', true); end if;
  select count(*)::integer into used_count from public.forum_action_log where user_id = current_user_id and action = p_action and created_at >= now() - interval '1 minute';
  if used_count >= max_per_minute then return jsonb_build_object('allowed', false, 'retry_after', 60, 'duplicate', false); end if;
  insert into public.forum_action_log(user_id, action, request_id) values (current_user_id, p_action, p_request_id);
  return jsonb_build_object('allowed', true, 'retry_after', 0, 'duplicate', false);
end; $$;
grant execute on function public.check_forum_rate_limit(text, uuid) to authenticated;

create or replace function public.sync_post_vote_counts()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if tg_op in ('DELETE','UPDATE') then
    update public.posts set upvotes = (select count(*) from public.votes where post_id = old.post_id and vote_type = 'up'), downvotes = (select count(*) from public.votes where post_id = old.post_id and vote_type = 'down') where id = old.post_id;
  end if;
  if tg_op in ('INSERT','UPDATE') and (tg_op = 'INSERT' or new.post_id is distinct from old.post_id) then
    update public.posts set upvotes = (select count(*) from public.votes where post_id = new.post_id and vote_type = 'up'), downvotes = (select count(*) from public.votes where post_id = new.post_id and vote_type = 'down') where id = new.post_id;
  elsif tg_op = 'UPDATE' then
    update public.posts set upvotes = (select count(*) from public.votes where post_id = new.post_id and vote_type = 'up'), downvotes = (select count(*) from public.votes where post_id = new.post_id and vote_type = 'down') where id = new.post_id;
  end if;
  return coalesce(new, old);
end; $$;
drop trigger if exists votes_sync_post_counts on public.votes;
create trigger votes_sync_post_counts after insert or update or delete on public.votes for each row execute function public.sync_post_vote_counts();

create unique index if not exists votes_user_post_unique on public.votes(user_id, post_id);
alter table public.votes drop constraint if exists votes_type_check;
alter table public.votes add constraint votes_type_check check (vote_type in ('up','down'));

create or replace function public.touch_forum_updated_at()
returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
drop trigger if exists posts_touch_updated_at on public.posts;
create trigger posts_touch_updated_at before update on public.posts for each row execute function public.touch_forum_updated_at();
drop trigger if exists comments_touch_updated_at on public.comments;
create trigger comments_touch_updated_at before update on public.comments for each row execute function public.touch_forum_updated_at();

create or replace function public.sync_post_reply_count()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if tg_op in ('DELETE','UPDATE') then
    update public.posts set replies = (select count(*) from public.comments where post_id = old.post_id and deleted_at is null) where id = old.post_id;
  end if;
  if tg_op in ('INSERT','UPDATE') and (tg_op = 'INSERT' or new.post_id is distinct from old.post_id) then
    update public.posts set replies = (select count(*) from public.comments where post_id = new.post_id and deleted_at is null) where id = new.post_id;
  elsif tg_op = 'UPDATE' then
    update public.posts set replies = (select count(*) from public.comments where post_id = new.post_id and deleted_at is null) where id = new.post_id;
  end if;
  return coalesce(new, old);
end; $$;
drop trigger if exists comments_sync_post_reply_count on public.comments;
create trigger comments_sync_post_reply_count after insert or update or delete on public.comments for each row execute function public.sync_post_reply_count();
