-- SkillHub 自动审核 Agent v1：规则预审、风险标记与可追溯记录。
-- 不删除真实内容；低风险自动发布，高风险保留待人工审核。

create table if not exists public.automated_moderation_runs (
  id bigint generated by default as identity primary key,
  target_type text not null check (target_type in ('post','comment')),
  target_id text not null,
  decision text not null check (decision in ('clean','flagged')),
  risk_score integer not null check (risk_score between 0 and 100),
  labels text[] not null default '{}',
  rule_version text not null default 'rules-v1',
  created_at timestamptz not null default now()
);
create index if not exists automated_moderation_runs_target_idx
  on public.automated_moderation_runs(target_type, target_id, created_at desc);
alter table public.automated_moderation_runs enable row level security;
revoke all on public.automated_moderation_runs from anon, authenticated;
grant select on public.automated_moderation_runs to authenticated;
drop policy if exists "Operators read moderation runs" on public.automated_moderation_runs;
create policy "Operators read moderation runs"
  on public.automated_moderation_runs for select to authenticated
  using (public.current_user_is_operator());

alter table public.posts add column if not exists automated_review_status text not null default 'not_run';
alter table public.posts add column if not exists automated_risk_score integer not null default 0;
alter table public.posts add column if not exists automated_labels text[] not null default '{}';
alter table public.posts add column if not exists automated_review_reason text;
alter table public.posts add column if not exists automated_reviewed_at timestamptz;
alter table public.posts add column if not exists automated_review_version text not null default 'rules-v1';
alter table public.comments add column if not exists automated_review_status text not null default 'not_run';
alter table public.comments add column if not exists automated_risk_score integer not null default 0;
alter table public.comments add column if not exists automated_labels text[] not null default '{}';
alter table public.comments add column if not exists automated_review_reason text;
alter table public.comments add column if not exists automated_reviewed_at timestamptz;
alter table public.comments add column if not exists automated_review_version text not null default 'rules-v1';

drop policy if exists "Published comments are public" on public.comments;
create policy "Published comments are public"
  on public.comments for select using (
    (deleted_at is null and status = 'published' and automated_review_status <> 'flagged' and exists (
      select 1 from public.posts p where p.id = comments.post_id and p.deleted_at is null and p.status = 'published'
    ))
    or user_id = auth.uid()
    or public.current_user_is_operator()
  );

alter table public.posts drop constraint if exists posts_automated_review_status_check;
alter table public.posts add constraint posts_automated_review_status_check
  check (automated_review_status in ('not_run','clean','flagged'));
alter table public.comments drop constraint if exists comments_automated_review_status_check;
alter table public.comments add constraint comments_automated_review_status_check
  check (automated_review_status in ('not_run','clean','flagged'));

create or replace function public.auto_moderation_score(p_text text)
returns jsonb language plpgsql immutable as $$
declare
  v text := lower(coalesce(p_text, ''));
  score integer := 0;
  labels text[] := '{}';
begin
  if v ~* '(博彩|赌博|色情|裸聊|诈骗|刷单|代写|贷款|投资返利|杀猪盘|赌博网站)' then
    score := score + 70; labels := array_append(labels, 'high_risk_term');
  end if;
  if v ~* '(加微信|微信号|vx|v信|telegram|whatsapp|二维码|联系我|手机号|手机号码|邮箱)' then
    score := score + 35; labels := array_append(labels, 'contact_exchange');
  end if;
  if v ~* '(https?://|www\.)' then
    score := score + 10; labels := array_append(labels, 'external_link');
  end if;
  if char_length(v) > 12000 then
    score := score + 20; labels := array_append(labels, 'overlong');
  end if;
  if v ~* '(.)\1\1\1\1\1\1\1\1' then
    score := score + 10; labels := array_append(labels, 'repeated_text');
  end if;
  score := least(score, 100);
  return jsonb_build_object(
    'decision', case when score >= 50 then 'flagged' else 'clean' end,
    'risk_score', score,
    'labels', to_jsonb(labels),
    'reason', case when cardinality(labels) = 0 then '规则未发现明显风险。' else array_to_string(labels, '、') end,
    'rule_version', 'rules-v1'
  );
end;
$$;
revoke all on function public.auto_moderation_score(text) from public, anon, authenticated;

create or replace function public.auto_moderate_post_row()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $$
declare
  result jsonb;
  decision text;
  score integer;
  labels text[];
  reason text;
begin
  if new.deleted_at is not null or new.status <> 'pending' then return new; end if;
  if tg_op = 'UPDATE' and old.status = 'pending' and old.title is not distinct from new.title and old.content is not distinct from new.content then return new; end if;
  result := public.auto_moderation_score(coalesce(new.title, '') || E'\n' || coalesce(new.content, ''));
  decision := result->>'decision';
  score := (result->>'risk_score')::integer;
  labels := array(select jsonb_array_elements_text(result->'labels'));
  reason := result->>'reason';
  new.automated_review_status := decision;
  new.automated_risk_score := score;
  new.automated_labels := labels;
  new.automated_review_reason := reason;
  new.automated_reviewed_at := now();
  new.automated_review_version := result->>'rule_version';
  if decision = 'clean' then
    new.status := 'published';
    new.rejection_reason := null;
    new.moderated_at := now();
    new.moderation_reason := '自动审核通过：' || reason;
  end if;
  insert into public.automated_moderation_runs(target_type,target_id,decision,risk_score,labels,rule_version)
  values ('post', new.id::text, decision, score, labels, result->>'rule_version');
  return new;
end;
$$;

create or replace function public.auto_moderate_comment_row()
returns trigger language plpgsql security definer set search_path = public, pg_temp as $$
declare
  result jsonb;
  decision text;
  score integer;
  labels text[];
  reason text;
begin
  if new.deleted_at is not null or new.status <> 'published' then return new; end if;
  if tg_op = 'UPDATE' and old.content is not distinct from new.content and old.status = 'published' then return new; end if;
  result := public.auto_moderation_score(new.content);
  decision := result->>'decision';
  score := (result->>'risk_score')::integer;
  labels := array(select jsonb_array_elements_text(result->'labels'));
  reason := result->>'reason';
  new.automated_review_status := decision;
  new.automated_risk_score := score;
  new.automated_labels := labels;
  new.automated_review_reason := reason;
  new.automated_reviewed_at := now();
  new.automated_review_version := result->>'rule_version';
  if decision = 'flagged' then
    new.moderation_reason := '自动审核转人工：' || reason;
  end if;
  insert into public.automated_moderation_runs(target_type,target_id,decision,risk_score,labels,rule_version)
  values ('comment', new.id::text, decision, score, labels, result->>'rule_version');
  return new;
end;
$$;

drop trigger if exists posts_auto_moderation on public.posts;
create trigger posts_auto_moderation
  before insert or update of title, content, status on public.posts
  for each row execute function public.auto_moderate_post_row();
drop trigger if exists comments_auto_moderation on public.comments;
create trigger comments_auto_moderation
  before insert or update of content, status on public.comments
  for each row execute function public.auto_moderate_comment_row();

grant execute on function public.auto_moderation_score(text) to authenticated;

create or replace function public.get_automated_moderation_queue(p_limit integer default 50)
returns table (
  target_type text,
  target_id text,
  post_id bigint,
  title text,
  author text,
  content text,
  risk_score integer,
  labels text[],
  created_at timestamptz
) language plpgsql security definer set search_path = public, pg_temp as $$
begin
  if not public.current_user_is_operator() then raise exception 'forbidden'; end if;
  return query
    select r.target_type,
           r.target_id,
           coalesce(p.id, c.post_id) as post_id,
           coalesce(p.title, '回复') as title,
           coalesce(p.author, c.author) as author,
           coalesce(p.content, c.content) as content,
           r.risk_score,
           r.labels,
           r.created_at
      from public.automated_moderation_runs r
      left join public.posts p on r.target_type = 'post' and p.id::text = r.target_id
      left join public.comments c on r.target_type = 'comment' and c.id::text = r.target_id
     where r.decision = 'flagged'
       and ((r.target_type = 'post' and p.status = 'pending' and p.deleted_at is null)
         or (r.target_type = 'comment' and c.automated_review_status = 'flagged' and c.deleted_at is null))
     order by r.created_at desc
     limit least(greatest(coalesce(p_limit, 50), 1), 100);
end;
$$;
grant execute on function public.get_automated_moderation_queue(integer) to authenticated;
